### ISSUE TITLE
Update to 1.20.4

### ISSUE THREAD

**Issue by bruh1273** [JackFred2/ChestTracker#111]
ChestTracker 1.20.4 formal support. 
Quality of life, no actual changes needed.

**Comment by JackFred2** [comment]
Currently waiting on a dependency update; it functions if you use a dependency override as seen here: https://github.com/JackFred2/ChestTracker/releases/tag/v2.1.2%2B1.20.4

**Comment by Ash3781** [comment]
i just tried the override but minecraft instantly crashes if you try to open the gui

**Comment by SirPotato42** [comment]
> i just tried the override but minecraft instantly crashes if you try to open the gui

Can confirm, the override crashes when opening the gui at all. The settings still work through mod menu.

[21:06:24] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoClassDefFoundError: com/blamejared/searchables/api/autcomplete/AutoCompletingEditBox
	at red.jackf.chesttracker.ChestTracker.openInGame(ChestTracker.java:71) ~[chesttracker-2.1.1+1.20.3.jar:?]
	at red.jackf.chesttracker.ChestTracker.lambda$onInitializeClient$3(ChestTracker.java:99) ~[chesttracker-2.1.1+1.20.3.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34) ~[fabric-lifecycle-events-v1-2.2.2+78d798af4f-64bd7b525ab8a9df.jar:?]
	at net.minecraft.class_310.handler$zef000$fabric-lifecycle-events-v1$onStartTick(class_310.java:4272) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.3.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: com.blamejared.searchables.api.autcomplete.AutoCompletingEditBox
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 14 more
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-01-01 21:06:25
Description: Unexpected error

java.lang.NoClassDefFoundError: com/blamejared/searchables/api/autcomplete/AutoCompletingEditBox
	at red.jackf.chesttracker.ChestTracker.openInGame(ChestTracker.java:71)
	at red.jackf.chesttracker.ChestTracker.lambda$onInitializeClient$3(ChestTracker.java:99)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$zef000$fabric-lifecycle-events-v1$onStartTick(class_310.java:4272)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ClassNotFoundException: com.blamejared.searchables.api.autcomplete.AutoCompletingEditBox
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 14 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at red.jackf.chesttracker.ChestTracker.openInGame(ChestTracker.java:71)
	at red.jackf.chesttracker.ChestTracker.lambda$onInitializeClient$3(ChestTracker.java:99)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$zef000$fabric-lifecycle-events-v1$onStartTick(class_310.java:4272)

-- Uptime --
Details:
	JVM uptime: 48.906s
	Wall uptime: 35.075s
	High-res time: 32.801s
	Client ticks: 585 ticks / 29.250s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:911)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 1 total; [class_746['SirPotato42'/685488, l='ClientLevel', x=-425.07, y=64.00, z=304.19]]
	Chunk stats: 2209, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (-115,69,168), Section: (at 13,5,8 in -8,4,10; chunk contains blocks -128,-64,160 to -113,319,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 783997634 game time, 825589836 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
	Tracked entity count: 275

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 180615216 bytes (172 MiB) / 851443712 bytes (812 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600X 6-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Parsec Virtual Display Adapter
	Graphics card #0 vendor: Parsec Cloud, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=0.41.0.0
	Graphics card #1 name: Radeon RX 5500 XT
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x7340
	Graphics card #1 versionInfo: DriverVersion=31.0.12027.9001
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 48551.75
	Virtual memory used (MB): 31237.89
	Swap memory total (MB): 15872.00
	Swap memory used (MB): 743.71
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8192m
	Fabric Mods: 
		chesttracker: Chest Tracker 2.1.1+1.20.3
			whereisit: WhereIsIt 2.3.0+1.20.3
				jackfredlib: JackFredLib 0.8.1+1.20.3
					jackfredlib-base: JackFredLib: Base 1.2.0+1.20.3
					jackfredlib-colour: JackFredLib: Colour 1.0.3+1.20.3
					jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.1.0+1.20.3
					jackfredlib-gps: JackFredLib: GPS 1.0.7+1.20.3
					jackfredlib-lying: JackFredLib: Lying 0.5.0+1.20.3
					jackfredlib-toasts: JackFredLib: Toasts 1.0.4+1.20.3
		fabric-api: Fabric API 0.92.0+1.20.4
			fabric-api-base: Fabric API Base 0.4.35+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.45+78d798af4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.15+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.14+78d798af4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.3+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.45+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.6+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.40+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.19+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.57+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.81+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.9+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.9+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.22+78d798af4f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.17+78d798af4f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.60+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.28+4ced05924f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.0+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.71+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.45+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.1.34+78d798af4f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.20+78d798af4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.40+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.38+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.29+78d798af4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.4+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.4+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.59+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.7+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.6+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.2+78d798af4f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.8+06274a474f
			fabric-particles-v1: Fabric Particles (v1) 1.1.6+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.15+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.13+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.3+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.3+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.50+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.41+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.32+78d798af4f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.53+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.12+78d798af4f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.13+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.15+78d798af4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.16+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.50+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.16+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.6+78d798af4f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.13+78d798af4f
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		java: Java HotSpot(TM) 64-Bit Server VM 17
		minecraft: Minecraft 1.20.4
		yet_another_config_lib_v3: YetAnotherConfigLib 3.3.1+1.20.4
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Launched Version: 1.20.4
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Radeon RX 5500 XT GL version 3.2.0 Core Profile Context 22.20.27.09.230330, ATI Technologies Inc.
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: fabric
	Current Language: en_us
	Locale: en_US
	CPU: 12x AMD Ryzen 5 3600X 6-Core Processor 
#@!@# Game crashed! Crash report saved to: #@!@# C

**Comment by elpocoburrito** [comment]
Searcheables got updated yesterday, but the update is only for 1.20.3. I did a PR to searcheables for 1.20.4, but either it needs to be approved by jaredlll08 or we need to build Chest Tracker with a local build of it.

I plan on giving a shot at option 2 myself, no promise.

[https://github.com/jaredlll08/searchables/pull/8](url)

**Comment by JackFred2** [comment]
I've rejigged a couple things to make Searchables optional; it'll now use it if it's installed separately or alongside another mod; without it some searching features will be disabled. 2.1.4

**Comment by JackFred2** [comment]
https://github.com/JackFred2/ChestTracker/releases/tag/v2.1.4%2B1.20.4 sorry for the delay
