### ISSUE TITLE
on search for any item, minecraft crashes to desktop

### ISSUE THREAD

**Issue by Ice129** [JackFred2/ChestTracker#163]
Opening the GUI and clicking any item, the world freezes then saves and closes out to desktop. 
here are the relevant logs

> [13:55:43] [Render thread/INFO]: Minimap updated server level id: 995755873 for world ResourceKey[minecraft:dimension / minecraft:overworld]
[13:55:43] [Render thread/INFO]: Loaded 853 advancements
[13:55:44] [Render thread/INFO]: Reloading entity icon resources...
[13:55:44] [Render thread/INFO]: Reloaded entity icon resources!
[13:55:44] [Render thread/WARN]: Class xaero.common.minimap.render.radar.EntityIconModelPartsRenderer$VertexConsumerWrapper does not support optimized vertex writing code paths, which may cause reduced rendering performance
[13:55:45] [Render thread/WARN]: Time from main menu to in-game was 9.423548 seconds
[13:55:45] [Render thread/WARN]: Total time to load game and open world was 46.41355 seconds
[13:55:51] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 6251ms or 125 ticks behind
[13:56:09] [Render thread/INFO]: [CHAT] Search Request:
[13:56:09] [Render thread/INFO]: [CHAT] Data: 
[13:56:09] [Render thread/INFO]: [CHAT] * Id:  "whereisit:item"
[13:56:09] [Render thread/INFO]: [CHAT]   Data: 
[13:56:09] [Render thread/INFO]: [CHAT]     ItemId: "minecraft:diamond_pickaxe"
[13:56:09] [Render thread/INFO]: [CHAT] * Id:  "whereisit:enchantment"
[13:56:09] [Render thread/INFO]: [CHAT]   Data: 
[13:56:09] [Render thread/INFO]: [CHAT]     EnchantmentId: "minecraft:efficiency"
[13:56:09] [Render thread/INFO]: [CHAT]     EnchantmentLevel: 2
[13:56:09] [Render thread/INFO]: [CHAT] * Id:  "whereisit:enchantment"
[13:56:09] [Render thread/INFO]: [CHAT]   Data: 
[13:56:09] [Render thread/INFO]: [CHAT]     EnchantmentId: "minecraft:silk_touch"
[13:56:09] [Render thread/INFO]: [CHAT]     EnchantmentLevel: 1
[13:56:09] [Render thread/INFO]: [CHAT] * Id:  "whereisit:enchantment"
[13:56:09] [Render thread/INFO]: [CHAT]   Data: 
[13:56:09] [Render thread/INFO]: [CHAT]     EnchantmentId: "minecraft:unbreaking"
[13:56:09] [Render thread/INFO]: [CHAT]     EnchantmentLevel: 2
[13:56:09] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:180) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:180) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.2.jar:?]
	at dynamic_fps.impl.util.event.InputObserver.onPress(InputObserver.java:96) ~[dynamic-fps-3.4.3+minecraft-1.20.0-fabric.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:220) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:287) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1349) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
Caused by: java.lang.NoClassDefFoundError: red/jackf/chesttracker/provider/ProviderHandler
	at fewwan.xaerosmapchesttrackerintegration.plugin.WhereIsItXaerosMapChestTrakerIntegrationPlugin.onResults(WhereIsItXaerosMapChestTrakerIntegrationPlugin.java:53) ~[xaeros-map-chest-tracker-integration-mc1.20.4-v2.0.1.jar:?]
	at red.jackf.whereisit.client.api.events.OnResult.lambda$static$0(OnResult.java:16) ~[whereisit-2.4.1+1.20.4.jar:?]
	at red.jackf.whereisit.client.WhereIsItClient.recieveResults(WhereIsItClient.java:128) ~[whereisit-2.4.1+1.20.4.jar:?]
	at red.jackf.chesttracker.impl.compat.mods.ChestTrackerWhereIsItPlugin.lambda$load$0(ChestTrackerWhereIsItPlugin.java:23) ~[chesttracker-2.4.3+1.20.4.jar:?]
	at red.jackf.whereisit.client.api.events.SearchInvoker.lambda$static$0(SearchInvoker.java:20) ~[whereisit-2.4.1+1.20.4.jar:?]
	at red.jackf.whereisit.client.WhereIsItClient.doSearch(WhereIsItClient.java:113) ~[whereisit-2.4.1+1.20.4.jar:?]
	at red.jackf.whereisit.client.api.events.SearchInvoker.doSearch(SearchInvoker.java:35) ~[whereisit-2.4.1+1.20.4.jar:?]
	at red.jackf.chesttracker.impl.gui.widget.ItemListWidget.method_25348(ItemListWidget.java:78) ~[chesttracker-2.4.3+1.20.4.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at red.jackf.chesttracker.impl.gui.screen.ChestTrackerScreen.method_25402(ChestTrackerScreen.java:383) ~[chesttracker-2.4.3+1.20.4.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	... 18 more
Caused by: java.lang.ClassNotFoundException: red.jackf.chesttracker.provider.ProviderHandler
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at fewwan.xaerosmapchesttrackerintegration.plugin.WhereIsItXaerosMapChestTrakerIntegrationPlugin.onResults(WhereIsItXaerosMapChestTrakerIntegrationPlugin.java:53) ~[xaeros-map-chest-tracker-integration-mc1.20.4-v2.0.1.jar:?]
	at red.jackf.whereisit.client.api.events.OnResult.lambda$static$0(OnResult.java:16) ~[whereisit-2.4.1+1.20.4.jar:?]
	at red.jackf.whereisit.client.WhereIsItClient.recieveResults(WhereIsItClient.java:128) ~[whereisit-2.4.1+1.20.4.jar:?]
	at red.jackf.chesttracker.impl.compat.mods.ChestTrackerWhereIsItPlugin.lambda$load$0(ChestTrackerWhereIsItPlugin.java:23) ~[chesttracker-2.4.3+1.20.4.jar:?]
	at red.jackf.whereisit.client.api.events.SearchInvoker.lambda$static$0(SearchInvoker.java:20) ~[whereisit-2.4.1+1.20.4.jar:?]
	at red.jackf.whereisit.client.WhereIsItClient.doSearch(WhereIsItClient.java:113) ~[whereisit-2.4.1+1.20.4.jar:?]
	at red.jackf.whereisit.client.api.events.SearchInvoker.doSearch(SearchInvoker.java:35) ~[whereisit-2.4.1+1.20.4.jar:?]
	at red.jackf.chesttracker.impl.gui.widget.ItemListWidget.method_25348(ItemListWidget.java:78) ~[chesttracker-2.4.3+1.20.4.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:38) ~[client-intermediary.jar:?]
	at red.jackf.chesttracker.impl.gui.screen.ChestTrackerScreen.method_25402(ChestTrackerScreen.java:383) ~[chesttracker-2.4.3+1.20.4.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	... 18 more
[13:56:09] [Server thread/INFO]: Stopping server
[13:56:09] [Server thread/INFO]: Saving players
[13:56:09] [Server thread/INFO]: Saving worlds

**Comment by Ice129** [comment]
issue with intergration with "WhereIsItXaerosMapChestTrakerIntegrationPlugin"
