### ISSUE TITLE
Jade 1.21 Integration Class not found

### ISSUE THREAD

**Issue by minhperry** [JackFred2/ChestTracker#166]
```14 Jun 2024, 16:00:06
INSTANCE
java.lang.NoClassDefFoundError: snownee/jade/api/Identifiers
	at red.jackf.chesttracker.impl.compat.mods.jade.JadeClientContentsPreview.appendTooltip(JadeClientContentsPreview.java:36)
	at red.jackf.chesttracker.impl.compat.mods.jade.JadeClientContentsPreview.appendTooltip(JadeClientContentsPreview.java:29)
	at snownee.jade.impl.BlockAccessorClientHandler.gatherComponents(BlockAccessorClientHandler.java:93)
	at snownee.jade.impl.BlockAccessorClientHandler.gatherComponents(BlockAccessorClientHandler.java:24)
	at snownee.jade.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:194)
	at snownee.jade.util.ClientProxy.onClientTick(ClientProxy.java:139)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$zhd000$fabric-lifecycle-events-v1$onEndTick(class_310.java:4683)
	at net.minecraft.class_310.method_1574(class_310.java:2012)
	at net.minecraft.class_310.method_1523(class_310.java:1246)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.ClassNotFoundException: snownee.jade.api.Identifiers
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 18 more```

**Comment by JackFred2** [comment]
fixed in 2.4.6, out in a few mins
