### ISSUE TITLE
Placing chests with auto add enabled crashed game. (1.20.6 Feather Client)

### ISSUE THREAD

**Issue by tristan-chenoweth** [JackFred2/ChestTracker#168]
With the setting "Auto-add Placed Blocks" toggled to yes causes game to crash in 1.20.6 using Feather Client. Unsure if it happens with other clients. I also have other mods added as well. 

If more information on this is needed let me know I will keep the crash report. 

Here is the stacktrace from the crash log. 
```
Stacktrace:
	at red.jackf.chesttracker.api.providers.defaults.DefaultProvider.lambda$onBlockPlaced$3(DefaultProvider.java:82)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at red.jackf.chesttracker.api.providers.defaults.DefaultProvider.onBlockPlaced(DefaultProvider.java:73)
	at red.jackf.chesttracker.impl.providers.ProviderHandler.lambda$setupEvents$5(ProviderHandler.java:88)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at red.jackf.chesttracker.impl.providers.ProviderHandler.lambda$setupEvents$6(ProviderHandler.java:81)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at red.jackf.chesttracker.impl.providers.ProviderHandler.lambda$setupEvents$7(ProviderHandler.java:80)
	at red.jackf.chesttracker.impl.events.AfterPlayerPlaceBlock.lambda$static$0(AfterPlayerPlaceBlock.java:16)
	at net.minecraft.class_1747.handler$zzc000$chesttracker$afterBlockPlace(class_1747.java:540)
	at net.minecraft.class_1747.method_7712(class_1747.java:91)
	at net.minecraft.class_1747.method_7884(class_1747.java:46)
	at net.minecraft.class_1799.method_7981(class_1799.java:365)
	at net.minecraft.class_636.method_41934(class_636.java:367)
	at net.minecraft.class_636.method_41933(class_636.java:319)
	at net.minecraft.class_636.method_41931(class_636.java:280)
	at net.minecraft.class_636.method_2896(class_636.java:318)
	at net.minecraft.class_310.method_1583(class_310.java:1902)
	at net.minecraft.class_310.method_1508(class_310.java:2158)
```

**Comment by JackFred2** [comment]
Can you upload the full crash report? Though because it's a closed source client I might be limited in what I can do.On 17 Jun 2024 06:35, Tristan Chenoweth ***@***.***> wrote:
With the setting "Auto-add Placed Blocks" toggled to yes causes game to crash in 1.20.6 using Feather Client. Unsure if it happens with other clients. I also have other mods added as well.
If more information on this is needed let me know I will keep the crash report.
Here is the stacktrace from the crash log.
Stacktrace:
	at red.jackf.chesttracker.api.providers.defaults.DefaultProvider.lambda$onBlockPlaced$3(DefaultProvider.java:82)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at red.jackf.chesttracker.api.providers.defaults.DefaultProvider.onBlockPlaced(DefaultProvider.java:73)
	at red.jackf.chesttracker.impl.providers.ProviderHandler.lambda$setupEvents$5(ProviderHandler.java:88)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at red.jackf.chesttracker.impl.providers.ProviderHandler.lambda$setupEvents$6(ProviderHandler.java:81)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at red.jackf.chesttracker.impl.providers.ProviderHandler.lambda$setupEvents$7(ProviderHandler.java:80)
	at red.jackf.chesttracker.impl.events.AfterPlayerPlaceBlock.lambda$static$0(AfterPlayerPlaceBlock.java:16)
	at net.minecraft.class_1747.handler$zzc000$chesttracker$afterBlockPlace(class_1747.java:540)
	at net.minecraft.class_1747.method_7712(class_1747.java:91)
	at net.minecraft.class_1747.method_7884(class_1747.java:46)
	at net.minecraft.class_1799.method_7981(class_1799.java:365)
	at net.minecraft.class_636.method_41934(class_636.java:367)
	at net.minecraft.class_636.method_41933(class_636.java:319)
	at net.minecraft.class_636.method_41931(class_636.java:280)
	at net.minecraft.class_636.method_2896(class_636.java:318)
	at net.minecraft.class_310.method_1583(class_310.java:1902)
	at net.minecraft.class_310.method_1508(class_310.java:2158)

**Comment by tristan-chenoweth** [comment]
Here is the full crash report.
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-06-16 22:19:41
Description: Unexpected error

java.lang.NoSuchMethodError: 'java.util.stream.Stream org.apache.commons.lang3.stream.Streams.of(java.lang.Iterable)'
	at red.jackf.chesttracker.api.providers.defaults.DefaultProvider.lambda$onBlockPlaced$3(DefaultProvider.java:82)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at red.jackf.chesttracker.api.providers.defaults.DefaultProvider.onBlockPlaced(DefaultProvider.java:73)
	at red.jackf.chesttracker.impl.providers.ProviderHandler.lambda$setupEvents$5(ProviderHandler.java:88)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at red.jackf.chesttracker.impl.providers.ProviderHandler.lambda$setupEvents$6(ProviderHandler.java:81)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at red.jackf.chesttracker.impl.providers.ProviderHandler.lambda$setupEvents$7(ProviderHandler.java:80)
	at red.jackf.chesttracker.impl.events.AfterPlayerPlaceBlock.lambda$static$0(AfterPlayerPlaceBlock.java:16)
	at net.minecraft.class_1747.handler$zzc000$chesttracker$afterBlockPlace(class_1747.java:540)
	at net.minecraft.class_1747.method_7712(class_1747.java:91)
	at net.minecraft.class_1747.method_7884(class_1747.java:46)
	at net.minecraft.class_1799.method_7981(class_1799.java:365)
	at net.minecraft.class_636.method_41934(class_636.java:367)
	at net.minecraft.class_636.method_41933(class_636.java:319)
	at net.minecraft.class_636.method_41931(class_636.java:280)
	at net.minecraft.class_636.method_2896(class_636.java:318)
	at net.minecraft.class_310.method_1583(class_310.java:1902)
	at net.minecraft.class_310.method_1508(class_310.java:2158)
	at net.minecraft.class_310.method_1574(class_310.java:1989)
	at net.minecraft.class_310.method_1523(class_310.java:1281)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at red.jackf.chesttracker.api.providers.defaults.DefaultProvider.lambda$onBlockPlaced$3(DefaultProvider.java:82)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at red.jackf.chesttracker.api.providers.defaults.DefaultProvider.onBlockPlaced(DefaultProvider.java:73)
	at red.jackf.chesttracker.impl.providers.ProviderHandler.lambda$setupEvents$5(ProviderHandler.java:88)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at red.jackf.chesttracker.impl.providers.ProviderHandler.lambda$setupEvents$6(ProviderHandler.java:81)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at red.jackf.chesttracker.impl.providers.ProviderHandler.lambda$setupEvents$7(ProviderHandler.java:80)
	at red.jackf.chesttracker.impl.events.AfterPlayerPlaceBlock.lambda$static$0(AfterPlayerPlaceBlock.java:16)
	at net.minecraft.class_1747.handler$zzc000$chesttracker$afterBlockPlace(class_1747.java:540)
	at net.minecraft.class_1747.method_7712(class_1747.java:91)
	at net.minecraft.class_1747.method_7884(class_1747.java:46)
	at net.minecraft.class_1799.method_7981(class_1799.java:365)
	at net.minecraft.class_636.method_41934(class_636.java:367)
	at net.minecraft.class_636.method_41933(class_636.java:319)
	at net.minecraft.class_636.method_41931(class_636.java:280)
	at net.minecraft.class_636.method_2896(class_636.java:318)
	at net.minecraft.class_310.method_1583(class_310.java:1902)
	at net.minecraft.class_310.method_1508(class_310.java:2158)

-- Uptime --
Details:
	JVM uptime: 45.480s
	Wall uptime: 34.276s
	High-res time: 28.462s
	Client ticks: 399 ticks / 19.950s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2548)
	at net.minecraft.class_310.method_54580(class_310.java:983)
	at net.minecraft.class_310.method_1514(class_310.java:911)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

-- Affected level --
Details:
	All players: 1 total; [class_746['DarkShadow12671'/968037, l='ClientLevel', x=-2271.24, y=123.00, z=2276.39]]
	Chunk stats: 1024, 201
	Level dimension: minecraft:overworld
	Level spawn location: World: (-2287,4,2015), Section: (at 1,4,15 in -143,0,125; chunk contains blocks -2288,-64,2000 to -2273,319,2015), Region: (-5,3; contains chunks -160,96 to -129,127, blocks -2560,-64,1536 to -2049,319,2047)
	Level time: 402153898 game time, 403802041 day time
	Server brand: Pufferfish (Velocity)
	Server type: Non-integrated multiplayer server
	Tracked entity count: 198

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, chesttracker, cloth-config, emi, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, feather, iris, jackfredlib, jackfredlib-base, jackfredlib-colour, jackfredlib-extracommandsourcedata, jackfredlib-gps, jackfredlib-lying, jackfredlib-toasts, jei, physicsmod, searchables, shulkerboxtooltip, skinlayers3d, sodium, whereisit, xaerominimap, xaeroworldmap, yet_another_config_lib_v3, file/Sapixcraft 64x 1.19.4.zip, server/00000000/8c2800bb-4cd1-382a-92cd-bd63bb92a95b

-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1272108576 bytes (1213 MiB) / 2449473536 bytes (2336 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MB): 12288.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.15.5222
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 75177.27
	Virtual memory used (MB): 43870.89
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 157.71
	JVM Flags: 8 total; -Xmx12288M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ErrorFile=feather/java_error.log
	Fabric Mods: 
		chesttracker: Chest Tracker 2.4.4+1.20.6
			whereisit: Where Is It 2.4.3+1.20.6
				jackfredlib: JackFredLib 0.10.0+1.20.5
					jackfredlib-base: JackFredLib: Base 1.4.0+1.20.5
					jackfredlib-colour: JackFredLib: Colour 1.1.0+1.20.5
					jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.1.1+1.20.5
					jackfredlib-gps: JackFredLib: GPS 1.0.7+1.20.5
					jackfredlib-lying: JackFredLib: Lying 0.5.5+1.20.5
					jackfredlib-toasts: JackFredLib: Toasts 1.1.0+1.20.5
		cloth-config: Cloth Config v14 14.0.126
			cloth-basic-math: cloth-basic-math 0.6.1
		emi: EMI 1.1.7+1.20.6+fabric
		fabric-api: Fabric API 0.99.0+1.20.6
			fabric-api-base: Fabric API Base 0.4.40+80f8cf51b0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.59+e9d2a72bb0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.25+be5d88beb0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.20+6dfe4c9bb0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.8+80f8cf51b0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.50+80f8cf51b0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.12+7f945d5bb0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.45+f71b366fb0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.24+80f8cf51b0
			fabric-commands-v0: Fabric Commands (v0) 0.2.62+df3654b3b0
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.5+b82b2392b0
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.4+7f945d5bb0
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.1.0+70fd1b46b0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.27+80f8cf51b0
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.16+2a2c66b6b0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 19.2.0+a5d5299db0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.68+94793913b0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.8+e9d2a72bb0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.6+c5fc38b3b0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.50+80f8cf51b0
			fabric-item-api-v1: Fabric Item API (v1) 8.2.1+8e8943b6b0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.39+aae0949ab0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.45+80f8cf51b0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.43+df3654b3b0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.4+c5fc38b3b0
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.5+97f703dab0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.11+a7dc0e41b0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.12+80f8cf51b0
			fabric-models-v0: Fabric Models (v0) 0.4.11+9386d8a7b0
			fabric-networking-api-v1: Fabric Networking API (v1) 4.0.8+0dca0349b0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.4+c5fc38b3b0
			fabric-particles-v1: Fabric Particles (v1) 4.0.0+c5fc38b3b0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.3+c5fc38b3b0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.16+ad474493b0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.12+97f703dab0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.12+80f8cf51b0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.61+df3654b3b0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.46+73761d2eb0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.3+2c869dedb0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.64+df3654b3b0
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.4+b21c00cbb0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.2.0+a5d5299db0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.0+c0e5481fb0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.21+7b70ea8ab0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.73+8c7b71c2b0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.21+c5fc38b3b0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.6+c5fc38b3b0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.10+74e2f560b0
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		feather: Feather Client release/fb88f094
		iris: Iris 1.7.1+mc1.20.6
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		jei: Just Enough Items 18.0.0.62
		minecraft: Minecraft 1.20.6
		mousetweaks: Mouse Tweaks 2.26
		physicsmod: Physics Mod 3.0.14
		searchables: Searchables 1.0.1
		shulkerboxtooltip: Shulker Box Tooltip 4.1.0-alpha.4+1.20.6
		skinlayers3d: 3d-Skin-Layers 1.6.6
		sodium: Sodium 0.5.9+mc1.20.6
		xaerominimap: Xaero's Minimap 24.2.0
		xaeroworldmap: Xaero's World Map 1.38.8
		yet_another_config_lib_v3: YetAnotherConfigLib 3.4.4+1.20.6-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Loaded Shaderpack: (off)
	Launched Version: 1.20.6-feather
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 552.22, NVIDIA Corporation
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'Feather Fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 6/32 chunks
	Resource Packs: vanilla, fabric, chesttracker, cloth-config, emi, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, feather (incompatible), iris, jackfredlib, jackfredlib-base, jackfredlib-colour, jackfredlib-extracommandsourcedata, jackfredlib-gps, jackfredlib-lying, jackfredlib-toasts, jei (incompatible), physicsmod, searchables (incompatible), shulkerboxtooltip, skinlayers3d, sodium, whereisit, xaerominimap (incompatible), xaeroworldmap (incompatible), yet_another_config_lib_v3 (incompatible), file/Sapixcraft 64x 1.19.4.zip (incompatible), server/00000000/8c2800bb-4cd1-382a-92cd-bd63bb92a95b (incompatible)
	Current Language: en_us
	Locale: en_US
	CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
```

**Comment by JackFred2** [comment]
Looks indeed to be a Feather issue unfortunately; I can't reproduce the crash on a MultiMC setup with the same mods.

My best guess though, looking at other people's Feather crashes, is that the launcher is installing the wrong Apache lang3 jar. I can't be 100% sure though.
