### ISSUE TITLE
Container label still inside block(s) above

### ISSUE THREAD

**Issue by ash-development** [JackFred2/ChestTracker#196]
Hi! I found that the commit that was made referencing #44 didn't exactly solve the issue of chest labels still being inside blocks above it. In the screenshot below, the label is still inside of the chest above it.
![image](https://github.com/user-attachments/assets/96fd08db-c022-4ab8-be65-09c333a22c8d)
I also find this happens with 100% solid blocks (tested with dirt & birch planks)

**Comment by JackFred2** [comment]
Misread the screenshot; that commit was for a very old version. Rendering isn't my forte so I'll have a proper look at this after some other issues, but I'll see if I can bring that back.

**Comment by ash-development** [comment]
ah understood. i know this may sound simpler than it actually is, but i believe all that is needed is to check what direction the block is facing, and then place the label accordingly. and then put that inside logic that detects blocks on top

im taking a crack at it right now, ill lyk how it works out :)

**Comment by ash-development** [comment]
update: i got the labels in front of the chests. now i have to write the logic for blocks above 🫡

**Comment by ash-development** [comment]
aaaaaand done :3
![image](https://github.com/user-attachments/assets/e4eb8e86-aff3-4777-97f8-0f9f14cd0473)

**Comment by aswheaton** [comment]
Surely it is best to just make the position configurable? a slider in the config for y-offset of the label would basically solve this problem.

**Comment by ash-development** [comment]
@aswheaton i mean a y-offset wouldn't necessarily fix it? if i had a stack of 3 chests it wouldn't make much sense, where would the labels then go?

**Comment by ash-development** [comment]
after some testing with the latest updates, it appears that the chest label now highlights when you hover over the chest, but doesn't seem ideal. i have to re-do my PR to incorporate new changes, but maybe in that process i will make that an option in the menu.

**Comment by ash-development** [comment]
@JackFred2 any chance i could get some help over [in my fork](https://github.com/ash-development/ChestTracker/tree/1.21.1-newLabelSys)? i have the beginnings of the setting implementation but i can't seem to figure out what this crash is about - happens when i click the setting to change the state. ([here are the changes ive made btw](https://github.com/ash-development/ChestTracker/commit/be8e061dc81e69255cffcc024967421fe63b2995), im sure i just missed something)

```cmd
[23:57:21] [Render thread/ERROR] (Minecraft) Reported exception thrown!
 net.minecraft.ReportedException: Rendering screen
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:922) ~[minecraft-clientOnly-6224587501-1.21.1-loom.mappings.1_21_1.layered+hash.1212190944-v2.jar:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1285) ~[minecraft-clientOnly-6224587501-1.21.1-loom.mappings.1_21_1.layered+hash.1212190944-v2.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:882) [minecraft-clientOnly-6224587501-1.21.1-loom.mappings.1_21_1.layered+hash.1212190944-v2.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:256) [minecraft-clientOnly-6224587501-1.21.1-loom.mappings.1_21_1.layered+hash.1212190944-v2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.2.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
	at dev.isxander.yacl3.impl.SafeBinding.getValue(SafeBinding.java:17) ~[yet-another-config-lib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.impl.OptionImpl.changed(OptionImpl.java:107) ~[yet-another-config-lib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.controllers.ControllerWidget.render(ControllerWidget.java:43) ~[yet-another-config-lib-3.5.0+1.21-fabric.jar:?]
	at dev.isxander.yacl3.gui.OptionListWidget$OptionEntry.render(OptionListWidget.java:310) ~[yet-another-config-lib-3.5.0+1.21-fabric.jar:?]
	at net.minecraft.client.gui.components.AbstractSelectionList.renderItem(AbstractSelectionList.java:447) ~[minecraft-clientOnly-6224587501-1.21.1-loom.mappings.1_21_1.layered+hash.1212190944-v2.jar:?]
	at dev.isxander.yacl3.gui.ElementListWidgetExt.renderListItems(ElementListWidgetExt.java:214) ~[yet-another-config-lib-3.5.0+1.21-fabric.jar:?]
	at net.minecraft.client.gui.components.AbstractSelectionList.renderWidget(AbstractSelectionList.java:188) ~[minecraft-clientOnly-6224587501-1.21.1-loom.mappings.1_21_1.layered+hash.1212190944-v2.jar:?]
	at dev.isxander.yacl3.gui.ElementListWidgetExt.renderWidget(ElementListWidgetExt.java:77) ~[yet-another-config-lib-3.5.0+1.21-fabric.jar:?]
	at net.minecraft.client.gui.components.AbstractWidget.render(AbstractWidget.java:66) ~[minecraft-clientOnly-6224587501-1.21.1-loom.mappings.1_21_1.layered+hash.1212190944-v2.jar:?]
	at dev.isxander.yacl3.gui.tab.ListHolderWidget.renderWidget(ListHolderWidget.java:37) ~[yet-another-config-lib-3.5.0+1.21-fabric.jar:?]
	at net.minecraft.client.gui.components.AbstractWidget.render(AbstractWidget.java:66) ~[minecraft-clientOnly-6224587501-1.21.1-loom.mappings.1_21_1.layered+hash.1212190944-v2.jar:?]
	at net.minecraft.client.gui.screens.Screen.render(Screen.java:128) ~[minecraft-clientOnly-6224587501-1.21.1-loom.mappings.1_21_1.layered+hash.1212190944-v2.jar:?]
	at net.minecraft.client.gui.screens.Screen.renderWithTooltip(Screen.java:117) ~[minecraft-clientOnly-6224587501-1.21.1-loom.mappings.1_21_1.layered+hash.1212190944-v2.jar:?]
	at net.minecraft.client.renderer.GameRenderer.mixinextras$bridge$renderWithTooltip$177(GameRenderer.java) ~[minecraft-clientOnly-6224587501-1.21.1-loom.mappings.1_21_1.layered+hash.1212190944-v2.jar:?]
	at net.minecraft.client.renderer.GameRenderer.wrapOperation$zce000$fabric-screen-api-v1$onRenderScreen(GameRenderer.java:2086) ~[minecraft-clientOnly-6224587501-1.21.1-loom.mappings.1_21_1.layered+hash.1212190944-v2.jar:?]
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:913) ~[minecraft-clientOnly-6224587501-1.21.1-loom.mappings.1_21_1.layered+hash.1212190944-v2.jar:?]
	... 7 more
[23:57:21] [Server thread/INFO] (Minecraft) Stopping server
```

**Comment by JackFred2** [comment]
I can't reproduce the config loading issue on your fork; it might just be a case of deleting the dev config because of an old (invalid) value.
![image](https://github.com/user-attachments/assets/1da72b34-5d63-420e-9a9d-c596fc238f01)

Will add some comments on the PR
