### ISSUE TITLE
Breaking Containers Sometimes Crashes the Game

### ISSUE THREAD

**Issue by Boobies** [JackFred2/ChestTracker#20]
I got this behavior a bunch of times in the past but never got around to reporting it.

```
[12:09:53] [main/FATAL]: Unreported exception thrown!
java.lang.NegativeArraySizeException: null
	at java.util.AbstractCollection.toArray(AbstractCollection.java:136) ~[?:1.8.0_282]
	at java.util.ArrayList.<init>(ArrayList.java:178) ~[?:1.8.0_282]
	at red.jackf.chesttracker.memory.MemoryUtils.checkValidCycle(MemoryUtils.java:218) ~[chesttracker-1.16.5-0.8.8.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$6(ClientTickEvents.java:111) ~[e4500da3-d708-4b41-9b41-b8c1f9752124.jar:?]
	at net.minecraft.class_638.handler$bnk000$tickWorldAfterBlockEntities(class_638.java:4957) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:557) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:176) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1556) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1021) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.5-client.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-loader-0.11.3.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.3.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[12:09:53] [Server thread/INFO]: Unregistering com.sk89q.worldedit.fabric.FabricPlatform from WorldEdit
[12:09:53] [Server thread/INFO]: Stopping server
[12:09:53] [Server thread/INFO]: Saving players
[12:09:53] [Server thread/INFO]: Saving worlds
[12:09:53] [Server thread/INFO]: Saving chunks for level 'ServerLevel[RS Testing World]'/minecraft:overworld
[12:09:53] [Netty Server IO #1/ERROR]: Error saving file for singleplayer-RS Testing World
[12:09:53] [Netty Server IO #1/ERROR]: java.lang.IllegalArgumentException: Illegal Capacity: -1
[12:09:53] [Netty Local Client IO #0/INFO]: Found data for singleplayer-RS Testing World
[12:09:53] [Netty Local Client IO #0/INFO]: Empty file found for singleplayer-RS Testing World
[12:09:53] [Netty Local Client IO #0/INFO]: Loaded singleplayer-RS Testing World
[12:09:53] [Netty Server IO #1/INFO]: Saved data for singleplayer-RS Testing World
[12:09:53] [Netty Local Client IO #0/INFO]: Saved data for singleplayer-RS Testing World
[12:09:53] [Netty Local Client IO #0/INFO]: Found data for singleplayer-RS Testing World
[12:09:53] [Netty Local Client IO #0/INFO]: Loaded singleplayer-RS Testing World
[12:09:53] [Netty Local Client IO #0/INFO]: Saved data for singleplayer-RS Testing World
[12:09:53] [Server thread/INFO]: ThreadedAnvilChunkStorage (RS Testing World): All chunks are saved
[12:09:53] [Server thread/INFO]: Saving chunks for level 'ServerLevel[RS Testing World]'/minecraft:the_nether
[12:09:53] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:09:53] [Server thread/INFO]: Saving chunks for level 'ServerLevel[RS Testing World]'/minecraft:the_end
[12:09:53] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:09:53] [Server thread/INFO]: ThreadedAnvilChunkStorage (RS Testing World): All chunks are saved
[12:09:53] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:09:53] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:09:53] [main/INFO]: Stopping worker threads
```

**Comment by JackFred2** [comment]
I've pushed a hopeful fix for this (same issue as [something a while back](https://github.com/JackFred2/ChestTracker/commit/d6e7952e435605e0338f1cea3dc8a1c05869c5db) which I thought I fixed) in 0.8.10; if it still occurs feel free to reopen with another crash log.
