### ISSUE TITLE
AbstractMethodError Crash with Litematica

### ISSUE THREAD

**Issue by Kjegla** [JackFred2/ChestTracker#250]
**Issue Description**
The game crashes when trying to render the screen because the ModIcon class in the ChestTracker mod is missing the renderAt method required by the IGuiIcon interface.

**Steps to Reproduce:**
1. Install ChestTracker and Litematica.
2. Open Material List (M+L).
3. Game crash.

**Crash Log:**

>  java.lang.AbstractMethodError: Receiver class red.jackf.chesttracker.impl.compat.mods.litematica.ModIcon does not define or inherit an implementation of the resolved method 'abstract void renderAt(int, int, float, boolean, boolean, net.minecraft.class_332)' of interface fi.dy.masa.malilib.gui.interfaces.IGuiIcon.
    at knot//fi.dy.masa.malilib.gui.widgets.WidgetInfoIcon.render(WidgetInfoIcon.java:24)
    at knot//fi.dy.masa.malilib.gui.GuiBase.drawWidgets(GuiBase.java:632)
    at knot//fi.dy.masa.malilib.gui.GuiBase.method_25394(GuiBase.java:181)
    at knot//net.minecraft.class_437.method_47413(class_437.java:116)
    at knot//net.minecraft.class_757.mixinextras$bridge$method_47413$87(class_757.java)
    at knot//net.minecraft.class_757.wrapOperation$baa000$fabric-screen-api-v1$onRenderScreen(class_757.java:912)
    at knot//net.minecraft.class_757.method_3192(class_757.java:549)
    at knot//net.minecraft.class_310.method_1523(class_310.java:1352)
    at knot//net.minecraft.class_310.method_1514(class_310.java:933)
    at knot//net.minecraft.client.main.Main.main(Main.java:265)

**System and Mod Details:**
- Minecraft Version: 1.21.3
- Fabric Loader Version: 0.16.9

**Comment by JackFred2** [comment]
Fixed in 2.6.3
