### ISSUE TITLE
Game crashes when starting Chest Tracker 1.19.4

### ISSUE THREAD

**Issue by HyperdrivzZ** [JackFred2/ChestTracker#86]
**To Reproduce**
I just put the chesttracker 1.19.4 mod file in my Feather Client mods folder

**Crash Report**
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-05-03 16:05:18
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5944.setSampler(int, Object)" because "shaderinstance" is null
	at net.minecraft.class_761.method_3251(class_761.java:2363)
	at net.minecraft.class_761.method_22710(class_761.java:1714)
	at net.minecraft.class_757.method_3188(class_757.java:1616)
	at net.minecraft.class_757.method_3192(class_757.java:1247)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.method_3251(class_761.java:2363)
	at net.minecraft.class_761.method_22710(class_761.java:1714)
	at net.minecraft.class_757.method_3188(class_757.java:1616)

-- Affected level --
Details:
	All players: 1 total; [class_746['AyanZ__'/182392, l='ClientLevel', x=-272.25, y=69.00, z=389.29]]
	Chunk stats: 441, 201
	Level dimension: minecraft:overworld
	Level spawn location: World: (-203,69,517), Section: (at 5,5,5 in -13,4,32; chunk contains blocks -208,-64,512 to -193,319,527), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,-64,512 to -1,319,1023)
	Level time: 193090823 game time, 1033248 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:582)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, Fabric Mods
	Recovery: Yes
	Recovery reason: java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:198)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:163)
	at net.minecraft.class_1255.method_5383(class_1255.java:140)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)
Caused by: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at net.minecraft.class_2960.method_12830(class_2960.java:88)
	at net.minecraft.class_2960.<init>(class_2960.java:51)
	at net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram.rewriteAsId(FabricShaderProgram.java:42)
	at net.minecraft.class_5944.modify$zlk000$fabric-rendering-v1$modifyProgramId(class_5944.java:654)
	at net.minecraft.class_5944.localvar$bic000$optifabric$modifyProgramID(class_5944.java:1634)
	at net.minecraft.class_5944.<init>(class_5944.java:114)
	at net.minecraft.class_5944.<init>(class_5944.java:108)
	at net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram.<init>(FabricShaderProgram.java:28)
	at net.minecraft.class_757.mdf899a7$fabric-rendering-v1$lambda$registerShaders$0$0(class_757.java:1627)
	at io.github.cottonmc.cotton.gui.impl.client.LibGuiShaders.lambda$register$1(LibGuiShaders.java:18)
	at net.fabricmc.fabric.api.client.rendering.v1.CoreShaderRegistrationCallback.lambda$static$0(CoreShaderRegistrationCallback.java:44)
	at net.minecraft.class_757.handler$zli000$fabric-rendering-v1$registerShaders(class_757.java:1630)
	at net.minecraft.class_757.method_34538(class_757.java:536)
	at net.minecraft.class_757$1.method_45777(class_757.java:460)
	at net.minecraft.class_757$1.method_18788(class_757.java:432)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	... 18 more

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 713760792 bytes (680 MiB) / 1207959552 bytes (1152 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 2112.00
	Graphics card #0 deviceId: 0x0152
	Graphics card #0 versionInfo: DriverVersion=10.18.10.4358
	Graphics card #1 name: NVIDIA Quadro 2000
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x0dd8
	Graphics card #1 versionInfo: DriverVersion=21.21.13.7783
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.33
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.33
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 17282.09
	Virtual memory used (MB): 10434.42
	Swap memory total (MB): 1024.00
	Swap memory used (MB): 164.43
	JVM Flags: 8 total; -Xmx6144M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ErrorFile=feather/java_error.log
	Fabric Mods: 
		architectury: Architectury 8.1.79
		chesttracker: Chest Tracker 1.1.21
			libgui: LibGui 7.0.0-beta.2+1.19.4
				jankson: Jankson 5.0.1+j1.2.2
					blue_endless_jankson: jankson 1.2.2
				libninepatch: LibNinePatch 1.2.0
			whereisit: Where Is It 1.14.16
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		controlling: Controlling For Fabric 11.0.0.2
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		fabric-api: Fabric API 0.78.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.23+9ff28bcef4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.24+49abcf7ef4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.6+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.33+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.14+1134c5b8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.26+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.5+e719b857f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.43+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.53+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.8+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.0+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.7+5da15ca1f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.44+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.12+e45f7c65f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.42+a1ccd7bff4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.51+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.32+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.16+09a3510cf4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.4+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.32+c477957ef4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.30+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.14+5da15ca1f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.26+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.30+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+1ee8be40f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.38+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.29+11ba9c3bf4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.0+a6f3ccfaf4
			fabric-networking-v0: Fabric Networking (v0) 0.3.40+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.2+63b515f4f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.22+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.7+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.3+a383ab97f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.4+81e8c576f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.0+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.37+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.27+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.20+f1e4495bf4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.40+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.0+8f878217f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.1+1e1fb126f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.44+8c25edb4f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.19+5da15ca1f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e98211f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.0+d51205dbf4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.2+63b515f4f4
		fabric-language-kotlin: Fabric Language Kotlin 1.9.4+kotlin.1.8.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.19
		feather: Feather Client 1.0.0-SNAPSHOT
		inventoryprofilesnext: Inventory Profiles Next 1.9.7
		java: OpenJDK 64-Bit Server VM 17
		libipn: libIPN 2.0.7
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.2.2
		optifabric: OptiFabric 1.13.24
			mm: Manningham Mills 2.3
		roughlyenoughitems: Roughly Enough Items 11.0.597
			error_notifier: Error Notifier 1.0.9
		shulkerboxtooltip: Shulker Box Tooltip 3.2.5+1.19.4
		starlight: Starlight 1.1.1+fabric.ae22326
	Launched Version: 1.19.4-feather
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Quadro 2000/PCIe/SSE2 GL version 3.2.0 NVIDIA 377.83, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Unknown parameter enum.' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'Feather Fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: 
	Current Language: en_us
	CPU: 4x Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.19.4_HD_U_I3
	OptiFine Build: 20230324-183832
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 377.83
	OpenGlRenderer: Quadro 2000/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.19.4
	OptiFine jar version: OptiFine_1.19.4_HD_U_I3
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/Googl/AppData/Roaming/.minecraft/.optifine/OptiFine_1.19.4_HD_U_I3/Optifine-mapped.jar
	OptiFabric error: <None>

**Additional context**
Add any other context about the problem here. Post your crash log (in your `crash-reports` folder) if you can.

**Comment by HyperdrivzZ** [comment]
I am using Optifine Fabric,
Starlight
Entity Culling
Inventory Profiles Next
Better Statistics Screen (Fabric/Forge)
Jade
Quick Elytra
Roughly Enough Items (REI)
Inventory HUD +

**Comment by JackFred2** [comment]
Hi,
Unfortunately Feather Client's fabric mod seems to be closed source so I cannot check how it touches shader code (& breaks libgui).

 If you can, I'd recommend updating Fabric API to 0.80.0+1.19.4 or using these mods a different way (such as in a manual instance), but otherwise I don't have any ability to debug this. Apologies.
